jobs:
- job: buildAndTest
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.13'
      windows:
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
  - use: node
    version: 10.x
  - restoreCache: package-lock.json
  - script: npm install
  - script: npm test
  - saveCache:
    key: package-lock.json
    paths: node_modules

- job: publish
  dependsOn: buildAndTest
  steps:
  - use: node
    auth: my-npm-registry-svc-connection
  - script: npm publish
